body:
- type: markdown
  value: "# Element Request"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to start a new discussion! If you need real-time help, join us on Discord.
- type: textarea
  id: element_description
  attributes:
    label: Description
    description: "Describe the element and its functionality in-depth. Answering questions like Why is it useful, How customizable is it, etc, will improve chances of being approved."
    placeholder: "E.g. A <Spacer /> element such as that in SwiftUI. This would be useful as..."
  validations:
    required: true
- type: dropdown
  id: request_type
  attributes:
    label: Request Type
    options:
      - Addition (create new element)
      - Removal (remove existing element)
      - Modification (modify existing element – create minor or major change)
      - Depreciation/Replacement (depreciate or replace element with another one)
