export type ContentType =
  | "application/json"
  | "application/xml"
  | "application/javascript"
  | "application/pdf"
  | "application/x-www-form-urlencoded"
  | "application/zip"
  | "application/vnd.ms-excel"
  | "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  | "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
  | "application/vnd.openxmlformats-officedocument.presentationml.presentation"
  | "application/rtf"
  | "application/octet-stream"
  | "text/plain"
  | "text/html"
  | "text/css"
  | "text/csv"
  | "text/javascript"
  | "text/xml"
  | "image/jpeg"
  | "image/png"
  | "image/gif"
  | "image/webp"
  | "image/svg+xml"
  | "image/bmp"
  | "image/x-icon"
  | "audio/mpeg"
  | "audio/ogg"
  | "audio/wav"
  | "audio/webm"
  | "video/mp4"
  | "video/mpeg"
  | "video/webm"
  | "video/ogg"
  | "multipart/form-data"
  | "multipart/byteranges"
  | string;

export function isContentType(t: unknown): t is ContentType {
  return typeof t === "string";
}
