
// This file is auto-generated by scripts/generateRoutes.js
import { Page } from '@Aevium'

export interface Routes {
  [key: string]: Routes | (() => Promise<{ default: typeof Page }>); // Nested routes or import function
}

export const routes: Routes = {
  "admin": {},
  "ai": {},
  "www": {
    "index": () => import('../app/www/index'),
    "test": {
      "index": () => import('../app/www/test/index')
    }
  }
};
